/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'purnendu' at '1/21/17 10:18 AM' with Gradle 2.13
 *
 * @author purnendu, @date 1/21/17 10:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
